# Use
#    @warnpcfail precompile(args...)
# if you want to be warned when a precompile directive fails
macro warnpcfail(ex::Expr)
    modl = __module__
    file = __source__.file === nothing ? "?" : String(__source__.file)
    line = __source__.line
    quote
        $(esc(ex)) || @warn """precompile directive
     $($(Expr(:quote, ex)))
 failed. Please report an issue in $($modl) (after checking for duplicates) or remove this directive.""" _file=$file _line=$line
    end
end


function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Int64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, UInt64, Bool, UInt64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Int64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, UInt64, Bool, UInt64, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Int64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, UInt64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Int64, Bool, Bool, UInt64, UInt64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Nothing, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, UInt64, Bool, UInt64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Nothing, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, UInt64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Nothing, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, UInt64, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Nothing, Bool, Bool, UInt64, UInt64, Float64, String, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", Int64, Bool, Nothing, Bool, Bool, UInt64, UInt64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", UInt64, Bool, UInt64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", UInt64, Bool, UInt64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", UInt64, Bool, UInt64, Bool, Bool, Int64, Int64, Float64, String, String, Bool, Float64, Int64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Bool, Int64, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
    isdefined(GNSSDecoder, Symbol("##GPSL1Data#7")) &&  @warnpcfail precompile(Tuple{GNSSDecoder.var"##GPSL1Data#7", UInt64, Bool, UInt64, Bool, Bool, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Type{GNSSDecoder.GPSL1Data}, GNSSDecoder.GPSL1Data})
end
